version: 0.2
phases:
install:
commands:
- echo install step...
pre_build:
commands:
- echo logging in to AWS ECR...
- $(aws ecr get-login --no-include-email --region us-east-1)
build:
commands:
- echo build Docker image on `date`
- cd src
- docker build -t <image name>:latest .
Auto-deploy your container to Fargate 9
- docker tag <image name>:latest <ECR repository URI>:latest
post_build:
commands:
- echo build Docker image complete `date`
- echo push latest Docker images to ECR...
- docker push <ECR repository URI>:latest
- echo Writing image definitions file...
- printf '[{"name":"<container name>","imageUri":"<ECR repository URI>:latest"}]' > imagedefinitions.json
artifacts:
files: imagedefinitions.json